### ISSUE TITLE
Really old CMake version

### ISSUE THREAD

**Issue by Malacath-92** [SemaiCZE/inicpp#12]
Is it really necessary to support a 10 year old CMake version? This severely inhibits the ability to make this library more usable as a submodule because the current CMake version used does not even have target_compile_options, thus inicpp is polluting CMAKE_CXX_FLAGS which no library should ever do. Not to mention the deprecation warnings that users get on newer versions.

**Comment by SemaiCZE** [comment]
Hi,
it's definitely not necessary. Which version do you have in mind? `3.11`? Do we need just a new version or some other modifications?
Thank you!

**Comment by Malacath-92** [comment]
I can probably fix a PR in the coming week with some suggestions and we can take it from there. As for a more modern version of CMake I would personally say anything past 3.1 is a big step from 2.x, 3.1 still being 6 years old and thus hopefully being supported on most OSes. So it's up to you what you want to support, but I'll target 3.1 for my PR if that is fine by you.
