### ISSUE TITLE
Store Windows path with drive letter followed by colon?

### ISSUE THREAD

**Issue by clawton** [SemaiCZE/inicpp#14]
Hi -
Nice library you have here.  I'm trying to store a windows path like "E:\foo\bar".  When I set() the value, it looks good in the ini file that I write.
However when I read it back, it gets split into two parts. "E" and "\foo\bar".  Is there a way to suppress this behavior?

Thanks!

**Comment by SemaiCZE** [comment]
Hi,

thanks. We take `,` and `:` as array fields separator, so you need to escape them. Take a look into our wiki (https://github.com/SemaiCZE/inicpp/wiki/INI-format-specification), just before the example.

When I try this manually:
```cpp
std::string get_config()
{
	std::string conf_str = ""
		"[Other]\n"
		"item1 = E\\:\\\\foo\\\\bar\n";
	return conf_str;
}


int main(void)
{
	config example_conf = parser::load(get_config());
	section &sect = example_conf["Other"];
	auto item1 = sect["item1"].get<string_ini_t>();
	std::cout << item1 << std::endl;
}
```

```
❯ ./test
E:\foo\bar
```

**Comment by clawton** [comment]
Thanks for the info!  Didn't see the part about delimiters in the value, guess I was going too fast!
