### ISSUE TITLE
After `make install` library files (*.so) are not found at runtime (fix included)

### ISSUE THREAD

**Issue by slaufmann** [SemaiCZE/inicpp#5]
After `make install` is performed the header files are located at /usr/local/include/inicpp which is fine. But the library (*.so) files are located at /usr/local/include which is rather unusual.

The pull request #4 I opened fixes this by setting a more common LIB_INSTALL_DIR in CMakeLists.txt.

Thanks for the work on this easy-to-use library. I would appreciate it if you accept the pull request.

**Comment by SemaiCZE** [comment]
Fixed by @slaufmann in PR #4
