### ISSUE TITLE
usage of std::equal causing assertion fail

### ISSUE THREAD

**Issue by j-warren-123** [SemaiCZE/inicpp#9]
I came across this problem when trying to parse a uint64_t with a value of "0".

L126/7 of string_utils.cpp.

				std::string binary_prefix = "0b";
				if (std::equal(binary_prefix.begin(), binary_prefix.end(), value.begin()))

According to cppreference this uses the following:

1,3) Returns true if the range [first1, last1) is equal to the range [first2, first2 + (last1 - first1)), and false otherwise

This calculates the distance (in terms of iterations, or in this case, chars) between first2 and last2 as the length of 1. If len(1) > len(2), then the second range can fall outside of the .end() iterator for 2. Or in other words, they compare the same range, but you need to make sure 2 is at least as long as 1.

len("0") < len("0b") so it gets to the assertion failing.

std::equal supports 4 args, perhaps this would fix it?

std::equal(binary_prefix.begin(), binary_prefix.end(), value.begin(), value.end())

**Comment by SemaiCZE** [comment]
@j-warren-123 Thank you for nice detailed report! I've just pushed a fix. I think that it's better to check the sizes, because the range `[value.begin(), value.end())` is longer (in most cases), so `std::equal` would return `false`.
